// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_map_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class MALonLatPoint extends NSObject  {
  //region constants
  static const String name__ = 'MALonLatPoint';

  
  //endregion

  //region creators
  static Future<MALonLatPoint> create__({ bool init = true /* ios only */ }) async {
    final refId = await MethodChannel('me.yohom/amap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('amap_map_fluttify'))).invokeMethod('ObjectFactory::createMALonLatPoint', {'init': init});
    final object = MALonLatPoint()..refId = refId..tag__ = 'amap_map_fluttify';
    return object;
  }
  
  static Future<List<MALonLatPoint>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('me.yohom/amap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('amap_map_fluttify'))).invokeMethod('ObjectFactory::create_batchMALonLatPoint', {'length': length, 'init': init});
  
    final List<MALonLatPoint> typedResult = resultBatch.map((result) => MALonLatPoint()..refId = result..tag__ = 'amap_map_fluttify').toList();
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<double> get_lat() async {
    final __result__ = await MethodChannel('me.yohom/amap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('amap_map_fluttify'))).invokeMethod("MALonLatPoint::get_lat", {'__this__': this});
    return __result__ == null ? null : (__result__);
  }
  
  Future<double> get_lon() async {
    final __result__ = await MethodChannel('me.yohom/amap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('amap_map_fluttify'))).invokeMethod("MALonLatPoint::get_lon", {'__this__': this});
    return __result__ == null ? null : (__result__);
  }
  
  //endregion

  //region setters
  Future<void> set_lat(double lat) async {
    await MethodChannel('me.yohom/amap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('amap_map_fluttify'))).invokeMethod('MALonLatPoint::set_lat', <String, dynamic>{'__this__': this, "lat": lat});
  
  
  }
  
  Future<void> set_lon(double lon) async {
    await MethodChannel('me.yohom/amap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('amap_map_fluttify'))).invokeMethod('MALonLatPoint::set_lon', <String, dynamic>{'__this__': this, "lon": lon});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}

extension MALonLatPoint_Batch on List<MALonLatPoint> {
  //region getters
  Future<List<double>> get_lat_batch() async {
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('amap_map_fluttify'))).invokeMethod("MALonLatPoint::get_lat_batch", [for (final __item__ in this) {'__this__': __item__}]);
  
    final typedResult = (resultBatch as List).cast<double>().map((__result__) => __result__).toList();
    return typedResult;
  }
  
  Future<List<double>> get_lon_batch() async {
    final resultBatch = await MethodChannel('me.yohom/amap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec('amap_map_fluttify'))).invokeMethod("MALonLatPoint::get_lon_batch", [for (final __item__ in this) {'__this__': __item__}]);
  
    final typedResult = (resultBatch as List).cast<double>().map((__result__) => __result__).toList();
    return typedResult;
  }
  
  //endregion

  //region setters
  Future<void> set_lat_batch(List<double> lat) async {
    await MethodChannel('me.yohom/amap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('MALonLatPoint::set_lat_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "lat": lat[__i__]}]);
  
  
  }
  
  Future<void> set_lon_batch(List<double> lon) async {
    await MethodChannel('me.yohom/amap_map_fluttify', StandardMethodCodec(FluttifyMessageCodec())).invokeMethod('MALonLatPoint::set_lon_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "lon": lon[__i__]}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}